/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * kwops API
 * kwops API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AllEmployees,
  DismissParams,
  EmployeeCreateDto,
  EmployeeDetailsDto,
  TeamAssembleInputDto,
  TeamDetailsDto
} from './orval.schemas'



  /**
 * @summary GET teams
 */
export const getAll = <TData = AxiosResponse<TeamDetailsDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/teams`,options
    );
  }

/**
 * @summary POST teams/assemble
 */
export const assembleDevelopersForTeam = <TData = AxiosResponse<void>>(
    teamAssembleInputDto: TeamAssembleInputDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/teams/assemble`,
      teamAssembleInputDto,options
    );
  }

/**
 * @summary GET employees/{number}
 */
export const getByNumber = <TData = AxiosResponse<EmployeeDetailsDto>>(
    number: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/employees/${number}`,options
    );
  }

/**
 * @summary GET employees
 */
export const getAllEmployees = <TData = AxiosResponse<AllEmployees>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/employees`,options
    );
  }

/**
 * @summary POST employees
 */
export const add = <TData = AxiosResponse<void>>(
    employeeCreateDto: EmployeeCreateDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/employees`,
      employeeCreateDto,options
    );
  }

/**
 * @summary POST employees/{number}/dismiss
 */
export const dismiss = <TData = AxiosResponse<void>>(
    number: string,
    params?: DismissParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/employees/${number}/dismiss`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export type GetAllResult = AxiosResponse<TeamDetailsDto[]>
export type AssembleDevelopersForTeamResult = AxiosResponse<void>
export type GetByNumberResult = AxiosResponse<EmployeeDetailsDto>
export type GetAllEmployeesResult = AxiosResponse<AllEmployees>
export type AddResult = AxiosResponse<void>
export type DismissResult = AxiosResponse<void>
