/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * kwops API
 * kwops API
 * OpenAPI spec version: 1.0.0
 */
export type DismissParams = {
withNotice?: boolean;
};

export interface EmployeeCreateDto {
  firstName?: string;
  lastName?: string;
  startDate?: string;
}

export interface EmployeeDetailsDto {
  endDate?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  number?: string;
  startDate?: string;
}

export interface AllEmployees {
  employees?: EmployeeDetailsDto[];
}

export interface TeamAssembleInputDto {
  requiredNumberOfDevelopers?: number;
  teamId?: string;
}

export interface DeveloperDetailsDto {
  firstName?: string;
  id?: string;
  lastName?: string;
  rating?: number;
}

export interface TeamDetailsDto {
  developers?: DeveloperDetailsDto[];
  id?: string;
  name?: string;
}

