/* tslint:disable */
/* eslint-disable */
/**
 * kwops API
 * kwops API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeveloperDetailsDto
 */
export interface DeveloperDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof DeveloperDetailsDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeveloperDetailsDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeveloperDetailsDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {number}
     * @memberof DeveloperDetailsDto
     */
    'rating'?: number;
}

