/* tslint:disable */
/* eslint-disable */
/**
 * kwops API
 * kwops API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeCreateDto
 */
export interface EmployeeCreateDto {
    /**
     * 
     * @type {string}
     * @memberof EmployeeCreateDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeCreateDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeCreateDto
     */
    'startDate'?: string;
}

