/* tslint:disable */
/* eslint-disable */
/**
 * kwops API
 * kwops API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeDetailsDto
 */
export interface EmployeeDetailsDto {
    /**
     * 
     * @type {number}
     * @memberof EmployeeDetailsDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailsDto
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailsDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailsDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailsDto
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDetailsDto
     */
    'endDate'?: string;
}

