/* tslint:disable */
/* eslint-disable */
/**
 * kwops API
 * kwops API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DeveloperDetailsDto } from './developer-details-dto';

/**
 * 
 * @export
 * @interface TeamDetailsDto
 */
export interface TeamDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof TeamDetailsDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamDetailsDto
     */
    'name'?: string;
    /**
     * 
     * @type {Array<DeveloperDetailsDto>}
     * @memberof TeamDetailsDto
     */
    'developers'?: Array<DeveloperDetailsDto>;
}

