/* tslint:disable */
/* eslint-disable */
/**
 * kwops API
 * kwops API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeamAssembleInputDto
 */
export interface TeamAssembleInputDto {
    /**
     * 
     * @type {string}
     * @memberof TeamAssembleInputDto
     */
    'teamId'?: string;
    /**
     * 
     * @type {number}
     * @memberof TeamAssembleInputDto
     */
    'requiredNumberOfDevelopers'?: number;
}

