/* tslint:disable */
/* eslint-disable */
/**
 * kwops API
 * kwops API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { TeamAssembleInputDto } from '../models';
// @ts-ignore
import { TeamDetailsDto } from '../models';
/**
 * TeamControllerApi - axios parameter creator
 * @export
 */
export const TeamControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary POST teams/assemble
         * @param {TeamAssembleInputDto} teamAssembleInputDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assembleDevelopersForTeam: async (teamAssembleInputDto: TeamAssembleInputDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamAssembleInputDto' is not null or undefined
            assertParamExists('assembleDevelopersForTeam', 'teamAssembleInputDto', teamAssembleInputDto)
            const localVarPath = `/teams/assemble`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teamAssembleInputDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeamControllerApi - functional programming interface
 * @export
 */
export const TeamControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeamControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary POST teams/assemble
         * @param {TeamAssembleInputDto} teamAssembleInputDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assembleDevelopersForTeam(teamAssembleInputDto: TeamAssembleInputDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assembleDevelopersForTeam(teamAssembleInputDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['TeamControllerApi.assembleDevelopersForTeam']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary GET teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TeamDetailsDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAll(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['TeamControllerApi.getAll']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * TeamControllerApi - factory interface
 * @export
 */
export const TeamControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeamControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary POST teams/assemble
         * @param {TeamAssembleInputDto} teamAssembleInputDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assembleDevelopersForTeam(teamAssembleInputDto: TeamAssembleInputDto, options?: any): AxiosPromise<void> {
            return localVarFp.assembleDevelopersForTeam(teamAssembleInputDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAll(options?: any): AxiosPromise<Array<TeamDetailsDto>> {
            return localVarFp.getAll(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TeamControllerApi - interface
 * @export
 * @interface TeamControllerApi
 */
export interface TeamControllerApiInterface {
    /**
     * 
     * @summary POST teams/assemble
     * @param {TeamAssembleInputDto} teamAssembleInputDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamControllerApiInterface
     */
    assembleDevelopersForTeam(teamAssembleInputDto: TeamAssembleInputDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary GET teams
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamControllerApiInterface
     */
    getAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<TeamDetailsDto>>;

}

/**
 * TeamControllerApi - object-oriented interface
 * @export
 * @class TeamControllerApi
 * @extends {BaseAPI}
 */
export class TeamControllerApi extends BaseAPI implements TeamControllerApiInterface {
    /**
     * 
     * @summary POST teams/assemble
     * @param {TeamAssembleInputDto} teamAssembleInputDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamControllerApi
     */
    public assembleDevelopersForTeam(teamAssembleInputDto: TeamAssembleInputDto, options?: RawAxiosRequestConfig) {
        return TeamControllerApiFp(this.configuration).assembleDevelopersForTeam(teamAssembleInputDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET teams
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TeamControllerApi
     */
    public getAll(options?: RawAxiosRequestConfig) {
        return TeamControllerApiFp(this.configuration).getAll(options).then((request) => request(this.axios, this.basePath));
    }
}

