name: Workflow to Generate Counterfact dummy data
on: [ push ]
jobs:
  generate-dummy-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: Run Counterfact command
        run: |
          { time timeout 30 npx counterfact@latest ./build/openapi/output.swagger.json api; } 2> time_output.txt
      - name: Cat time output
        if: always()
        run: cat time_output.txt
