name: Workflow to Generate OpenAPITools server and dummy data
on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
jobs:
  generate-dummy-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'openapi-generator-cli'
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Install
        run: npm install
      - name: Run OpenAPITools command
        run: |
          { time timeout 30 npm run generate-openapi; } 2> time_output.txt
      - name: Cat time output
        if: always()
        run: cat time_output.txt